### ISSUE TITLE
End of Line Sequence in Windows VS Code 

### ISSUE THREAD

**Issue by youenchene** [MickGyver/vscode-amiga-blitzbasic#14]
in VS Code on Windows, the "End of Line Sequence" needs to be LF rather than CRLF, as otherwise Blitz will complain about "Garbage at End of Line".

**Comment by MickGyver** [comment]
There is an extension for batch converting EOL sequences, maybe a similar idea could be integrated in the build/run process? https://github.com/keyoti/VSCode-ChangeAllEOL

**Comment by youenchene** [comment]
@MickGyver just added  a quick 7 lines typescript code. It make the job in a simple matter.
