### ISSUE TITLE
Can't open file error on Windows 10 / WinUAE + WB3.1, Blitz 2.1 & SuperTed 2.52

### ISSUE THREAD

**Issue by adam-ainsworth** [MickGyver/vscode-amiga-blitzbasic#20]
Hi,

I believe I have found the issue of Ted randomly complaining it can't open a file as I can recreate it reliably every time and have also fixed it manually - the path that is being piped through by VSCode contains Windows backslashes rather than Amiga forward slashes for directory separators. These just need to be substituted - see my screenshot.

Thanks very much for this excellent piece of work, I'm trying to get it working on Linux but FS-UAE isn't playing ball with me there!

Adam

![bb_vsc](https://user-images.githubusercontent.com/554151/210871745-05019549-2c5a-4748-8a8c-b26d9b5b05eb.png)

**Comment by youenchene** [comment]
Ok. Tx for identifying the issue. Not hard to fix, most of my time would be dedicated to setup the env within windows.

**Comment by youenchene** [comment]
Fix, done. need to do https://github.com/MickGyver/vscode-amiga-blitzbasic/issues/14 for full windows compatibility to publish.

**Comment by youenchene** [comment]
@adam-ainsworth correction published in version 0.9.1 : https://marketplace.visualstudio.com/items?itemName=MickGyver.amiga-blitzbasic2

**Comment by adam-ainsworth** [comment]
> @adam-ainsworth correction published in version 0.9.1 : https://marketplace.visualstudio.com/items?itemName=MickGyver.amiga-blitzbasic2

Thanks very much for sorting this out!
