### ISSUE TITLE
Random Couldn't open file with arexx script.

### ISSUE THREAD

**Issue by youenchene** [MickGyver/vscode-amiga-blitzbasic#7]
![image](https://user-images.githubusercontent.com/1607244/181238004-e05890b2-35cc-4d82-8fa6-ee14a5f9f830.png)

**Comment by MickGyver** [comment]
I merged your native java script version, has this error been fix with that merge?

**Comment by MickGyver** [comment]
I got a lot of these errors with WinUAE 6.0 x64. When I installed WinUAE x86 4.4, these errors seems to have completely vanished.
